Tablelizer [In Progress]
vembrane/vembrane pull request #79
Opened 2020-09-19 08:58 UTC by christopher-schroeder

Do not merge yet, pls

2020-09-21 09:58 UTC, tedil commented
TODO:

- [ ] write tests
- [ ] discuss naming
- [ ] discuss subcommand vs different entrypoint (i.e. `vembrane filter` and `vembrane table` vs `vembrane` and `vcftable`)

Questions:
- Does this only use fields that appear in the expression or is there a "dump everything" mode as well?

2020-09-21 10:12 UTC, tedil requested changes

2020-09-21 10:12 UTC, tedil commented on vembrane/modules/tablelize.py
> +    )
The help string needs updating ;)

2020-09-21 10:12 UTC, tedil commented on .flake8
> +    W503
why?

2020-09-21 10:12 UTC, tedil commented on vembrane/ann_types.py
> +        return "."
Should it really be `"."`? I'd rather have an empty cell or `None` or `NaN` I guess.

2020-09-22 13:02 UTC, tedil requested changes
Almost there! Some small things that need to be addressed and then we're good to go

2020-09-22 13:14 UTC, christopher-schroeder commented on vembrane/ann_types.py
> +
yes

2020-09-22 13:18 UTC, tedil approved these changes

2020-09-22 13:22 UTC, merged